[kafkaui]
namespace = ""
deployment = ""
env_configmap = ""
rbac_configmap = ""

[oauth]
authorization_endpoint = ""
token_endpoint = ""
jwks_uri = ""
redirect_uri = ""
client_id = ""
client_secret = ""
scope = ""
audience = ""
identity_field_in_token = ""

[mysql]
host = ""
port = 3306
database = ""
user = ""
password = ""